export const TYPES = {
    ADD_TO_CART: "ADD_TO_CART", /*AGREGA CIERTO ITEM AL CARRITO*/
    REMOVE_ITEM: "REMOVE_ITEMS", /*REMUEVE UNA UNIDAD DE CIERTO ITEM*/
    REMOVE_ALL_ITEMS: "REMOVE_ALL_ITEMS", /*REMUEVE TODAS LAS UNIDADES DE CIERTO ITEM*/
    CLEAR_CART: "CLEAR_CART", /*VUELVE EL CARRITO A CERO - BORRA TODO*/

};